### ISSUE TITLE
Please follow Node-RED node naming guidelines

### ISSUE THREAD

**Issue by knolleary** [autanalabs/node-red-appwrite#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes either use a scoped name `@your-org/xyx` or use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

I hope you'll consider it.

Many thanks, Nick

**Comment by gigonzalezs** [comment]
thanks Nick.

I added a note to the package description about moving the package to node-red-contrib-appwrite.

Regards

**Comment by gigonzalezs** [comment]
@knolleary package renamed to node-red-contrib-appwrite

Regards
